name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install -r requirements.txt
    - name: Lints each python file and fails if pylint score is less than 6.0
      run: |
            for file in $(find -name '*.py')
            do
              pylint --extension-pkg-whitelist='pydantic' --disable=E0401,W0611 "$file" --fail-under=6.0;
            done
